---
# -*- coding: utf-8 -*-

image: koalaman/shellcheck-alpine:stable

before_script:
  - shellcheck --version
  - apk update && apk add file grep make

stages:
  - shellcheck

shellcheck:
  stage: shellcheck
  script:
    - make syntax-check
