#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -z "$1" ]] && exit 1
[[ -e "$1" ]] || exit 1

REGEXP="$2"

grep "$REGEXP" "$1" | while read -r M D T _ LINE
do
  DATE=$(date --date "$M $D $T" '+%F %T')
  if [[ "$LINE" =~ pam_sss.*rec(eived|ibido).(for|para) ]]
  then
    ERROR_CODE="$(echo "$LINE" | awk '{print $6}')"
    PAM_ERROR="$(pam-error "$ERROR_CODE" | awk '{print $1}')"
    printf "%s %-26s %s\\n" "$DATE" "$PAM_ERROR" "$LINE"
  fi
done
