#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

KRB_ERRORS=$(cat << EOF
1765328384 KRB5KDC_ERR_NONE                   No error
1765328383 KRB5KDC_ERR_NAME_EXP               Client's entry in database has expired
1765328382 KRB5KDC_ERR_SERVICE_EXP            Server's entry in database has expired
1765328381 KRB5KDC_ERR_BAD_PVNO               Requested protocol version not supported
1765328380 KRB5KDC_ERR_C_OLD_MAST_KVNO        Client's key is encrypted in an old master key
1765328379 KRB5KDC_ERR_S_OLD_MAST_KVNO        Server's key is encrypted in an old master key
1765328378 KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN    Client not found in Kerberos database
1765328377 KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN    Server not found in Kerberos database
1765328376 KRB5KDC_ERR_PRINCIPAL_NOT_UNIQUE   Principal has multiple entries in Kerberos database
1765328375 KRB5KDC_ERR_NULL_KEY               Client or server has a null key
1765328374 KRB5KDC_ERR_CANNOT_POSTDATE        Ticket is ineligible for postdating
1765328373 KRB5KDC_ERR_NEVER_VALID            Requested effective lifetime is negative or too short
1765328372 KRB5KDC_ERR_POLICY                 KDC policy rejects request
1765328371 KRB5KDC_ERR_BADOPTION              KDC can't fulfill requested option
1765328370 KRB5KDC_ERR_ETYPE_NOSUPP           KDC has no support for encryption type
1765328369 KRB5KDC_ERR_SUMTYPE_NOSUPP         KDC has no support for checksum type
1765328368 KRB5KDC_ERR_PADATA_TYPE_NOSUPP     KDC has no support for padata type
1765328367 KRB5KDC_ERR_TRTYPE_NOSUPP          KDC has no support for transited type
1765328366 KRB5KDC_ERR_CLIENT_REVOKED         Client's credentials have been revoked
1765328365 KRB5KDC_ERR_SERVICE_REVOKED        Credentials for server have been revoked
1765328364 KRB5KDC_ERR_TGT_REVOKED            TGT has been revoked
1765328363 KRB5KDC_ERR_CLIENT_NOTYET          Client not yet valid — try again later
1765328362 KRB5KDC_ERR_SERVICE_NOTYET         Server not yet valid — try again later
1765328361 KRB5KDC_ERR_KEY_EXP                Password has expired
1765328360 KRB5KDC_ERR_PREAUTH_FAILED         Preauthentication failed
1765328359 KRB5KDC_ERR_PREAUTH_REQUIRED       Additional pre-authentication required
1765328358 KRB5KDC_ERR_SERVER_NOMATCH         Requested server and ticket don't match
1765328357 KRB5PLACEHOLD_27 through           KRB5 error codes 27
1765328354 KRB5PLACEHOLD_30 through           through 30 (reserved)
1765328353 KRB5KRB_AP_ERR_BAD_INTEGRITY       Decrypt integrity check failed
1765328352 KRB5KRB_AP_ERR_TKT_EXPIRED         Ticket expired
1765328351 KRB5KRB_AP_ERR_TKT_NYV             Ticket not yet valid
1765328350 KRB5KRB_AP_ERR_REPEAT              Request is a replay
1765328349 KRB5KRB_AP_ERR_NOT_US              The ticket isn't for us
1765328348 KRB5KRB_AP_ERR_BADMATCH            Ticket/authenticator don't match
1765328347 KRB5KRB_AP_ERR_SKEW                Clock skew too great
1765328346 KRB5KRB_AP_ERR_BADADDR             Incorrect net address
1765328345 KRB5KRB_AP_ERR_BADVERSION          Protocol version mismatch
1765328344 KRB5KRB_AP_ERR_MSG_TYPE            Invalid message type
1765328343 KRB5KRB_AP_ERR_MODIFIED            Message stream modified
1765328342 KRB5KRB_AP_ERR_BADORDER            Message out of order
1765328341 KRB5KRB_AP_ERR_ILL_CR_TKT          Illegal cross-realm ticket
1765328340 KRB5KRB_AP_ERR_BADKEYVER           Key version is not available
1765328339 KRB5KRB_AP_ERR_NOKEY               Service key not available
1765328338 KRB5KRB_AP_ERR_MUT_FAIL            Mutual authentication failed
1765328337 KRB5KRB_AP_ERR_BADDIRECTION        Incorrect message direction
1765328336 KRB5KRB_AP_ERR_METHOD              Alternative authentication method required
1765328335 KRB5KRB_AP_ERR_BADSEQ              Incorrect sequence number in message
1765328334 KRB5KRB_AP_ERR_INAPP_CKSUM         Inappropriate type of checksum in message
1765328333 KRB5PLACEHOLD_51                   KRB5 error codes 51 through 59 (reserved)
1765328324 KRB5KRB_ERR_GENERIC                Generic error
1765328323 KRB5KRB_ERR_FIELD_TOOLONG          Field is too long for this implementation
1765328322 KRB5PLACEHOLD_62                   KRB5 error codes 62 through 127 (reserved)
1765328256 VALUE_NOT_RETURNED                 For internal use only
1765328255 KRB5_LIBOS_BADLOCKFLAG             Invalid flag for file lock mode
1765328254 KRB5_LIBOS_CANTREADPWD             Cannot read password
1765328253 KRB5_LIBOS_BADPWDMATCH             Password mismatch
1765328252 KRB5_LIBOS_PWDINTR                 Password read interrupted
1765328251 KRB5_PARSE_ILLCHAR                 Illegal character in component name
1765328250 KRB5_PARSE_MALFORMED               Malformed representation of principal
1765328249 KRB5_CONFIG_CANTOPEN               Can't open/find Kerberos / etc/krb5/krb5 configuration file
1765328248 KRB5_CONFIG_BADFORMAT              Improper format of Kerberos /etc/krb5/krb5 configuration file
1765328247 KRB5_CONFIG_NOTENUFSPACE           Insufficient space to return complete information
1765328246 KRB5_BADMSGTYPE                    Invalid message type specified for encoding
1765328245 KRB5_CC_BADNAME                    Credential cache name malformed
1765328244 KRB5_CC_UNKNOWN_TYPE               Unknown credential cache type
1765328243 KRB5_CC_NOTFOUND                   Matching credential not found
1765328242 KRB5_CC_END                        End of credential cache reached
1765328241 KRB5_NO_TKT_SUPPLIED               Request did not supply a ticket
1765328240 KRB5KRB_AP_WRONG_PRINC             Wrong principal in request
1765328239 KRB5KRB_AP_ERR_TKT_INVALID         Ticket has invalid flag set
1765328238 KRB5_PRINC_NOMATCH                 Requested principal and ticket don't match
1765328237 KRB5_KDCREP_MODIFIED               KDC reply did not match expectations
1765328236 KRB5_KDCREP_SKEW                   Clock skew too great in KDC reply
1765328235 KRB5_IN_TKT_REALM_MISMATCH         Client/server realm mismatch in initial ticket request
1765328234 KRB5_PROG_ETYPE_NOSUPP             Program lacks support for encryption type
1765328233 KRB5_PROG_KEYTYPE_NOSUPP           Program lacks support for key type
1765328232 KRB5_WRONG_ETYPE                   Requested encryption type not used in message
1765328231 KRB5_PROG_SUMTYPE_NOSUPP           Program lacks support for checksum type
1765328230 KRB5_REALM_UNKNOWN                 Cannot find KDC for requested realm
1765328229 KRB5_SERVICE_UNKNOWN               Kerberos service unknown
1765328228 KRB5_KDC_UNREACH                   Cannot contact any KDC for requested realm
1765328227 KRB5_NO_LOCALNAME                  No local name found for principal name
1765328226 KRB5_MUTUAL_FAILED                 Mutual authentication failed
1765328225 KRB5_RC_TYPE_EXISTS                Replay cache type is already registered
1765328224 KRB5_RC_MALLOC                     No more memory to allocate (in replay cache code)
1765328223 KRB5_RC_TYPE_NOTFOUND              Replay cache type is unknown
1765328222 KRB5_RC_UNKNOWN                    Generic unknown RC error
1765328221 KRB5_RC_REPLAY                     Message is a replay
1765328220 KRB5_RC_IO                         Replay I/O operation failed
1765328219 KRB5_RC_NOIO                       Replay cache type does not support non-volatile storage
1765328218 KRB5_RC_PARSE                      Replay cache name parse/format error
1765328217 KRB5_RC_IO_EOF                     End-of-file on replay cache I/O
1765328216 KRB5_RC_IO_MALLOC                  No more memory to allocate (in replay cache I/O code)
1765328215 KRB5_RC_IO_PERM                    Permission denied in replay cache code
1765328214 KRB5_RC_IO_IO                      I/O error in replay cache i/o code
1765328213 KRB5_RC_IO_UNKNOWN                 Generic unknown RC/IO error
1765328212 KRB5_RC_IO_SPACE                   Insufficient system space to store replay information
1765328211 KRB5_TRANS_CANTOPEN                Can't open/find realm translation file
1765328210 KRB5_TRANS_BADFORMAT               Improper format of realm translation file
1765328209 KRB5_LNAME_CANTOPEN                Can't open/find lname translation database
1765328208 KRB5_LNAME_NOTRANS                 No translation available for requested principal
1765328207 KRB5_LNAME_BADFORMAT               Improper format of translation database entry
1765328206 KRB5_CRYPTO_INTERNAL               Cryptosystem internal error
1765328205 KRB5_KT_BADNAME                    Key table name malformed
1765328204 KRB5_KT_UNKNOWN_TYPE               Unknown Key table type
1765328203 KRB5_KT_NOTFOUND                   Key table entry not found
1765328202 KRB5_KT_END                        End of key table reached
1765328201 KRB5_KT_NOWRITE                    Cannot write to specified key table
1765328200 KRB5_KT_IOERR                      Error writing to key table
1765328199 KRB5_NO_TKT_IN_RLM                 Cannot find ticket for requested realm
1765328198 KRB5DES_BAD_KEYPAR                 DES key has bad parity
1765328197 KRB5DES_WEAK_KEY                   DES key is a weak key
1765328196 KRB5_BAD_ENCTYPE                   Bad encryption type
1765328195 KRB5_BAD_KEYSIZE                   Key size is incompatible with encryption type
1765328194 KRB5_BAD_MSIZE                     Message size is incompatible with encryption type
1765328193 KRB5_CC_TYPE_EXISTS                Credentials cache type is already registered
1765328192 KRB5_KT_TYPE_EXISTS                Key table type is already registered
1765328191 KRB5_CC_IO                         Credentials cache I/O operation failed
1765328190 KRB5_FCC_PERM                      Credentials cache file permissions incorrect
1765328189 KRB5_FCC_NOFILE                    No credentials cache file found
1765328188 KRB5_FCC_INTERNAL                  Internal file credentials cache error
1765328187 KRB5_CC_WRITE                      Error writing to credentials cache file
1765328186 KRB5_CC_NOMEM                      No more memory to allocate (in credentials cache code)
1765328185 KRB5_CC_FORMAT                     Bad format in credentials cache
1765328184 KRB5_INVALID_FLAGS                 Invalid KDC option combination (library internal error)
1765328183 KRB5_NO_2ND_TKT                    Request missing second ticket
1765328182 KRB5_NOCREDS_SUPPLIED              No credentials supplied to library routine
1765328181 KRB5_SENDAUTH_BADAUTHVERS          Bad sendauth version was sent
1765328180 KRB5_SENDAUTH_BADAPPLVERS          Bad application version was sent (by sendauth)
1765328179 KRB5_SENDAUTH_BADRESPONSE          Bad response (during sendauth exchange)
1765328178 KRB5_SENDAUTH_REJECTED             Server rejected authentication (during sendauth exchange)
1765328177 KRB5_PREAUTH_BAD_TYPE              Unsupported pre-authentication type
1765328176 KRB5_PREAUTH_NO_KEY                Required pre-authentication key not supplied
1765328175 KRB5_PREAUTH_FAILED                Generic preauthentication failure
1765328174 KRB5_RCACHE_BADVNO                 Unsupported replay cache format version number
1765328173 KRB5_CCACHE_BADVNO                 Unsupported credentials cache format version number
1765328172 KRB5_KEYTAB_BADVNO                 Unsupported key table format version number
1765328171 KRB5_PROG_ATYPE_NOSUPP             Program lacks support for address type
1765328170 KRB5_RC_REQUIRED                   Message replay detection requires rcache parameter
1765328169 KRB5_ERR_BAD_HOSTNAME              Host name cannot be canonicalized
1765328168 KRB5_ERR_HOST_REALM_UNKNOWN        Cannot determine realm for host
1765328167 KRB5_SNAME_UNSUPP_NAMETYPE         Conversion to service principal undefined for name type
1765328166 KRB5KRB_AP_ERR_V4_REPLY            Initial Ticket response appears to be Version 4 error
1765328165 KRB5_REALM_CANT_RESOLVE            Cannot resolve KDC for requested realm
1765328164 KRB5_TKT_NOT_FORWARDABLE           Requesting ticket can't get forwardable tickets
1765328163 KRB5_FWD_BAD_PRINCIPAL             Bad principal name while trying to forward credentials
1765328162 KRB5_GET_IN_TKT_LOOP               Looping detected inside krb5_get_in_tkt
1765328161 KRB5_CONFIG_NODEFREALM             Configuration file /etc/krb5 /krb5.conf does not specify default realm
1765328160 KRB5_SAM_UNSUPPORTED               Bad SAM flags in obtain_sam_padata
1765328159 KRB5_KT_NAME_TOOLONG               Keytab name too long
1765328158 KRB5_KT_KVNONOTFOUND               Key version number for principal in key table is incorrect
1765328157 KRB5_CONF_NOT_CONFIGURED           Kerberos /etc/krb5/krb5.conf configuration file not configured
1765328384 ERROR_TABLE_BASE_krb5              default
EOF
)

ERROR='.*'
[[ ! -z "$1" ]] && ERROR="${1//-/}"
echo "$KRB_ERRORS" | grep -E "$ERROR"
